version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=tic-tac-toe"
      HOME: /app/home
    volumes:
      - ".:/app"

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
      ROOT: "/app/public"
    volumes:
      - "./public:/app/public"
      - "./docker/nginx/templates:/etc/nginx/templates"
    depends_on:
      - php
      - swagger

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: "/app/tictactoe.yaml"
      #URL: "/doc"
    volumes:
      - "./:/app"
    ports:
      - "8080:8080"